In [15]:
from tensorflow.keras.preprocessing.text import one_hot

In [16]:
### Sentences
sent = [ 'the glass of milk',
         'the glass of juice',
         'the cup of tea',
         'I am a good boy',
         'I am a good developer',
        'understand the meaning of words',   
        'your videos are good']

In [17]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
## Define Vocabulary size
voc_size = 10000

In [19]:
## One hot representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr


[[6474, 5885, 7964, 8298],
 [6474, 5885, 7964, 692],
 [6474, 1490, 7964, 5919],
 [2250, 7782, 4059, 3511, 7229],
 [2250, 7782, 4059, 3511, 9852],
 [2064, 6474, 8570, 7964, 9993],
 [1551, 3522, 6356, 3511]]

In [20]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [21]:
import numpy as np
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 6474 5885 7964 8298]
 [   0    0    0    0 6474 5885 7964  692]
 [   0    0    0    0 6474 1490 7964 5919]
 [   0    0    0 2250 7782 4059 3511 7229]
 [   0    0    0 2250 7782 4059 3511 9852]
 [   0    0    0 2064 6474 8570 7964 9993]
 [   0    0    0    0 1551 3522 6356 3511]]


In [22]:
## feature representation
dim = 10

In [23]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam', 'mse')
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step


array([[[-0.00914006, -0.01020031,  0.01879222, -0.01322966,
         -0.01324474, -0.00797493, -0.04172172, -0.03921308,
          0.00206945, -0.00822542],
        [-0.00914006, -0.01020031,  0.01879222, -0.01322966,
         -0.01324474, -0.00797493, -0.04172172, -0.03921308,
          0.00206945, -0.00822542],
        [-0.00914006, -0.01020031,  0.01879222, -0.01322966,
         -0.01324474, -0.00797493, -0.04172172, -0.03921308,
          0.00206945, -0.00822542],
        [-0.00914006, -0.01020031,  0.01879222, -0.01322966,
         -0.01324474, -0.00797493, -0.04172172, -0.03921308,
          0.00206945, -0.00822542],
        [ 0.03335856,  0.04051514,  0.02750052, -0.01600575,
         -0.00212833, -0.01052879,  0.01713051, -0.02380594,
          0.01172614,  0.03570182],
        [-0.01289488,  0.04220692, -0.03906375, -0.03596476,
         -0.02286974, -0.00623735,  0.04811031, -0.00092267,
         -0.01311264,  0.04837762],
        [-0.03344103, -0.03891008, -0.04591272,  0.0